# Creating data table
## importing

In [1]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
PATH = Service("C:\Program Files (x86)\chromedriver.exe")

driver = webdriver.Chrome(service = PATH)
driver.close()

## Reading local csv

In [2]:
club_read = pd.read_csv("raw_datasets\clubs.csv")
club_read.head()

,club_id,name,pretty_name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,url
0,1032,fc-reading,Fc Reading,GB1,33.66,26,25.9,12,46.2,6,Select Car Leasing Stadium,24161,+£8.37m,Brian McDermott,https://www.transfermarkt.co.uk/fc-reading/sta...
1,2323,orduspor,Orduspor,TR1,NaN,0,NaN,0,NaN,0,19 Eylül Stadyum,11024,+-0,Héctor Cúper,https://www.transfermarkt.co.uk/orduspor/start...
2,1387,acn-siena-1904,Acn Siena 1904,IT1,4.32,30,26.2,6,20.0,2,Artemio Franchi,15373,£-6Th.,Serse Cosmi,https://www.transfermarkt.co.uk/acn-siena-1904...
3,3592,kryvbas-kryvyi-rig,Kryvbas Kryvyi Rig,UKR1,2.95,24,24.5,2,8.3,0,Shakhty Zhovtneva,2500,£-270Th.,Oleg Taran,https://www.transfermarkt.co.uk/kryvbas-kryvyi...
4,1071,wigan-athletic,Wigan Athletic,GB1,12.38,29,26.5,14,48.3,6,DW Stadium,25133,£-140Th.,Roberto Martínez,https://www.transfermarkt.co.uk/wigan-athletic...

In [3]:
competitions_read = pd.read_csv("raw_datasets\competitions.csv")
competitions_read.head()

,competition_id,name,type,country_id,country_name,domestic_league_code,confederation,url
0,L1,bundesliga,first_tier,40,Germany,L1,europa,https://www.transfermarkt.co.uk/bundesliga/sta...
1,DFB,dfb-pokal,domestic_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfb-pokal/star...
2,DFL,dfl-supercup,domestic_super_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfl-supercup/s...
3,NL1,eredivisie,first_tier,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/eredivisie/sta...
4,NLP,toto-knvb-beker,domestic_cup,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/toto-knvb-beke...

In [4]:
players_read = pd.read_csv("raw_datasets\players.csv")
players_read.head()

,player_id,last_season,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,url
0,254016,2013,855,arthur-delalande,Arthur Delalande,France,France,5/18/1992,Midfield,midfield - Central Midfield,Right,186,NaN,90000.0,https://www.transfermarkt.co.uk/arthur-delalan...
1,51053,2013,23,daniel-davari,Daniel Davari,Germany,Iran,1/6/1988,Goalkeeper,Goalkeeper,Right,192,135000.0,1130000.0,https://www.transfermarkt.co.uk/daniel-davari/...
2,31451,2013,23,torsten-oehrl,Torsten Oehrl,Germany,Germany,1/7/1986,Attack,attack - Centre-Forward,Right,192,NaN,1130000.0,https://www.transfermarkt.co.uk/torsten-oehrl/...
3,44622,2013,3691,vladimir-kisenkov,Vladimir Kisenkov,UdSSR,Russia,10/8/1981,Defender,Defender - Right-Back,Right,182,NaN,720000.0,https://www.transfermarkt.co.uk/vladimir-kisen...
4,30802,2013,3302,oscar-diaz,Oscar Diaz,Spain,Spain,4/24/1984,Attack,attack - Centre-Forward,Right,183,NaN,1080000.0,https://www.transfermarkt.co.uk/oscar-diaz/pro...

In [5]:
players_valuations_read = pd.read_csv("raw_datasets\player_valuations.csv")
players_valuations_read.head()

   player_id        date  market_value
0     254016  2013-07-22         90000
1     254016  2014-01-14         90000
2      51053  2008-08-25         90000
3      51053  2011-05-30         90000
4      51053  2011-08-26        225000

## Now begins the table handling

In [7]:
transfermarkt_url = [competitions_read.loc[competitions_read.domestic_league_code == x].iloc[0,7] 
       for x in ["GB1", "IT1", "ES1", "FR1", "L1"]]
transfermarkt_url

['https://www.transfermarkt.co.uk/premier-league/startseite/wettbewerb/GB1',
 'https://www.transfermarkt.co.uk/serie-a/startseite/wettbewerb/IT1',
 'https://www.transfermarkt.co.uk/laliga/startseite/wettbewerb/ES1',
 'https://www.transfermarkt.co.uk/ligue-1/startseite/wettbewerb/FR1',
 'https://www.transfermarkt.co.uk/bundesliga/startseite/wettbewerb/L1']

In [14]:
PATH = Service("C:\Program Files (x86)\chromedriver.exe")

driver = webdriver.Chrome(service = PATH)

team_names = []

# extract only teams currently in the league
for league_url in transfermarkt_url:
    driver.get(league_url)

    
    # get number of teams in the league
    league_details = driver.find_element("xpath", "(//tbody)").find_element("xpath", "(//tr)[2]").get_attribute('innerHTML')
    league_details.replace(' ','')
    start_stamp = league_details.find('<td>')+5
    end_stamp = league_details.find('teams',start_stamp)
    no_of_teams = int(league_details[start_stamp:end_stamp].strip())

    
    # get name of each team, matching club table convention
    search = driver.find_element("xpath", "(//tbody)[4]")
    for _ in range (1, no_of_teams+1):
        detail = search.find_element("xpath","(//td[@class='hauptlink no-border-links'])[%i]" %_).get_attribute('innerHTML')
        start_stamp = detail.find('/')+1
        end_stamp = detail.find('/',start_stamp)
        team_names.append(detail[start_stamp:end_stamp])

driver.close()

len(team_names)

98

In [15]:
filter_table = club_read.loc[(club_read.domestic_competition_id.isin(["GB1", "IT1", "ES1", "FR1", "L1"])) & (club_read.name.isin(team_names))].iloc[:,[0,1,2,3,-1]]

In [18]:
club_table = pd.DataFrame({'name':team_names}).merge(filter_table)
club_table

,name,club_id,pretty_name,domestic_competition_id,url
0,manchester-city,281,Manchester City,GB1,https://www.transfermarkt.co.uk/manchester-cit...
1,fc-liverpool,31,Fc Liverpool,GB1,https://www.transfermarkt.co.uk/fc-liverpool/s...
2,fc-chelsea,631,Fc Chelsea,GB1,https://www.transfermarkt.co.uk/fc-chelsea/sta...
3,manchester-united,985,Manchester United,GB1,https://www.transfermarkt.co.uk/manchester-uni...
4,tottenham-hotspur,148,Tottenham Hotspur,GB1,https://www.transfermarkt.co.uk/tottenham-hots...
...,...,...,...,...,...
93,hertha-bsc,44,Hertha Bsc,L1,https://www.transfermarkt.co.uk/hertha-bsc/sta...
94,1-fc-union-berlin,89,1 Fc Union Berlin,L1,https://www.transfermarkt.co.uk/1-fc-union-ber...
95,arminia-bielefeld,10,Arminia Bielefeld,L1,https://www.transfermarkt.co.uk/arminia-bielef...
96,vfl-bochum,80,Vfl Bochum,L1,https://www.transfermarkt.co.uk/vfl-bochum/sta...
97,spvgg-greuther-furth,65,Spvgg Greuther Furth,L1,https://www.transfermarkt.co.uk/spvgg-greuther...

In [30]:
for i in range(len(club_table.club_id)):
    if i == 0:
        mc_players = players_read.loc[(players_read.current_club_id == club_table.club_id[i])&(players_read.last_season == 2021)]
    else:
        club_players = players_read.loc[(players_read.current_club_id == club_table.club_id[i])&(players_read.last_season == 2021)]
        mc_players = pd.concat([mc_players,club_players])
        
mc_players = mc_players.iloc[:,[0,3,4,5,7,8,9,10]]

In [31]:
mc_players

,player_id,name,pretty_name,country_of_birth,date_of_birth,position,sub_position,foot
20224,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left
20228,363205,gabriel-jesus,Gabriel Jesus,Brazil,4/3/1997,Attack,attack - Centre-Forward,Right
20440,203460,jack-grealish,Jack Grealish,England,9/10/1995,Attack,attack - Left Winger,Right
20443,134425,raheem-sterling,Raheem Sterling,Jamaica,12/8/1994,Attack,attack - Left Winger,Right
20444,241641,bernardo-silva,Bernardo Silva,Portugal,8/10/1994,Attack,midfield - Attacking Midfield,Left
...,...,...,...,...,...,...,...,...
17578,36898,sascha-burchert,Sascha Burchert,DDR,10/30/1989,Goalkeeper,Goalkeeper,Right
17580,199221,andreas-linde,Andreas Linde,Sweden,7/24/1993,Goalkeeper,Goalkeeper,Right
17581,170517,marius-funk,Marius Funk,Germany,1/1/1996,Goalkeeper,Goalkeeper,Right
17583,161204,julian-green,Julian Green,United States,6/6/1995,Midfield,midfield - Central Midfield,Right
17604,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right

In [32]:
player_past = pd.merge(mc_players, players_valuations_read, on = ['player_id'])
player_past

,player_id,name,pretty_name,country_of_birth,date_of_birth,position,sub_position,foot,date,market_value
0,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left,2011-08-08,90000
1,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left,2011-09-03,180000
2,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left,2011-12-25,180000
3,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left,2012-06-01,270000
4,171424,riyad-mahrez,Riyad Mahrez,France,2/21/1991,Attack,attack - Right Winger,Left,2013-01-04,450000
...,...,...,...,...,...,...,...,...,...,...
50334,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right,2020-04-08,855000
50335,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right,2020-11-18,1800000
50336,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right,2021-02-08,1800000
50337,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right,2021-06-16,2250000
50338,183780,paul-seguin,Paul Seguin,Germany,3/29/1995,Midfield,midfield - Central Midfield,Right,2021-12-22,1980000

In [21]:
datelist = list(past_data.date)
datelist

['2014-09-30',
 '2015-02-17',
 '2015-07-01',
 '2016-02-24',
 '2016-07-15',
 '2017-02-22',
 '2017-06-26',
 '2018-02-27',
 '2018-08-13',
 '2018-12-19',
 '2019-06-13',
 '2019-12-10',
 '2020-04-08',
 '2020-10-13',
 '2021-03-18',
 '2021-06-01',
 '2021-12-23']

In [43]:
def endseason(date):
    return abs(sum(int(date[5:7])-i for i in [5,6,7,8,9]))

def date_extract(datelist):
    yearlist = {}
    for date in datelist:
        if not date[:4] in yearlist:
            yearlist[date[:4]] = date
        elif endseason(date) < endseason(yearlist[date[:4]]):
            yearlist[date[:4]] = date
        
    dateyear = {}
    for year in yearlist:
        dateyear[yearlist[year]] = year
    return yearlist, dateyear
            
date_extract(datelist)

({'2014': '2014-09-30',
  '2015': '2015-07-01',
  '2016': '2016-07-15',
  '2017': '2017-06-26',
  '2018': '2018-08-13',
  '2019': '2019-06-13',
  '2020': '2020-04-08',
  '2021': '2021-06-01'},
 {'2014-09-30': '2014',
  '2015-07-01': '2015',
  '2016-07-15': '2016',
  '2017-06-26': '2017',
  '2018-08-13': '2018',
  '2019-06-13': '2019',
  '2020-04-08': '2020',
  '2021-06-01': '2021'})

In [47]:
past_data = past_data.loc[past_data.date.isin(date_extract(list(past_data.date))[0].values())]
past_data.replace({"date":date_extract(list(past_data.date))[1]}).rename(columns = {"date":"year"})

,player_id,last_season,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,url,year,market_value
23,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2014,90000
25,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2015,630000
27,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2016,6300000
29,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2017,7200000
31,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2018,16200000
33,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2019,31500000
35,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2020,25200000
38,340950,2021,31,diogo-jota,Diogo Jota,Portugal,Portugal,12/4/1996,Attack,attack - Centre-Forward,Right,178,54000000.0,54000000.0,https://www.transfermarkt.co.uk/diogo-jota/pro...,2021,40500000